"""add unique constraint on gas_fillups odometer_miles

Revision ID: 75e36e6d3c42
Revises: 77a9b218cce6
Create Date: 2026-08-14 01:28:46.881288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e36e6d3c42'
down_revision: Union[str, Sequence[str], None] = '77a9b218cce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_gas_fillups_odometer_miles', 'gas_fillups', ['odometer_miles'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_gas_fillups_odometer_miles', 'gas_fillups', type_='unique')
    # ### end Alembic commands ###
