"""add gas_fillups gps_latitude/gps_longitude

Optional per-fillup GPS override, populated from a fill-up photo's EXIF data
when one is used. Not a reintroduction of the latitude/longitude columns
dropped in b624a2cb494e -- those were always a stale copy of the fill-up's
location row; these are a genuinely independent, more precise value (exact
photo GPS vs. city-level geocode), hence the different name. NULL means no
photo GPS was captured -- readers fall back to the joined location's
lat/long (see analytics.to_gas_out, mapping.build_route_data).

Revision ID: 77a9b218cce6
Revises: d5b785ff07a5
Create Date: 2026-08-14 00:44:49.842913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a9b218cce6'
down_revision: Union[str, Sequence[str], None] = 'd5b785ff07a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gas_fillups', sa.Column('gps_latitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('gas_fillups', sa.Column('gps_longitude', sa.Numeric(precision=9, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gas_fillups', 'gps_longitude')
    op.drop_column('gas_fillups', 'gps_latitude')
    # ### end Alembic commands ###
