"""initial schema

Revision ID: 853cc1c56d53
Revises: 
Create Date: 2026-08-12 10:00:55.924812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '853cc1c56d53'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gas_fillups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('odometer_miles', sa.Numeric(precision=10, scale=1), nullable=False),
    sa.Column('gallons', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('gallons > 0', name='ck_gas_fillups_gallons_positive'),
    sa.CheckConstraint('price >= 0', name='ck_gas_fillups_price_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gas_fillups_city_lower', 'gas_fillups', [sa.literal_column('lower(city)')], unique=False)
    op.create_index('idx_gas_fillups_date', 'gas_fillups', ['date'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('expense', sa.Text(), nullable=False),
    sa.Column('place', sa.Text(), nullable=False),
    sa.Column('odometer_miles', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('vendor', sa.Text(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_maintenance_records_date', 'maintenance_records', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_maintenance_records_date', table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index('idx_gas_fillups_date', table_name='gas_fillups')
    op.drop_index('idx_gas_fillups_city_lower', table_name='gas_fillups')
    op.drop_table('gas_fillups')
    # ### end Alembic commands ###
