"""add travel_data table

A general-purpose, dated + located event log -- see app/models.py's
TravelData docstring. entry_type is a native Postgres enum
(travel_entry_type); op.drop_table doesn't drop the enum type itself on
downgrade, so that's done explicitly below to avoid a leftover type
blocking a future re-upgrade.

Revision ID: a73c603de2a1
Revises: 75e36e6d3c42
Create Date: 2026-08-14 12:55:38.001624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a73c603de2a1'
down_revision: Union[str, Sequence[str], None] = '75e36e6d3c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('entry_type', sa.Enum('gas_fillup', 'grocery_pickup', 'overnight_stay', 'maintenance_event', name='travel_entry_type'), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('is_estimated_location', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travel_data')
    # ### end Alembic commands ###
    sa.Enum(name='travel_entry_type').drop(op.get_bind(), checkfirst=True)
