"""make maintenance_records.location_id required

Revision ID: d5b785ff07a5
Revises: 61111bf60c0e
Create Date: 2026-08-12 18:06:00.227696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5b785ff07a5'
down_revision: Union[str, Sequence[str], None] = '61111bf60c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maintenance_records', 'location_id',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maintenance_records', 'location_id',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
