"""add locations table

gas_fillups.city packs "City, State" into one field (e.g. "Lancaster, MA"),
inconsistently: a handful of rows have no comma/state at all, a couple omit
the space after the comma, and a few spell the state out in full instead of
abbreviating it. This migration splits on the first comma verbatim -- it
does not attempt to normalize those inconsistencies -- and backfills one
locations row per distinct (city, state) pair found in gas_fillups, reusing
that city's existing lat/lng.

Revision ID: f9f8c74f95a5
Revises: 853cc1c56d53
Create Date: 2026-08-12 10:10:03.524660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f8c74f95a5'
down_revision: Union[str, Sequence[str], None] = '853cc1c56d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('long', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_locations_city_state_lower', 'locations', [sa.literal_column('lower(city)'), sa.literal_column('lower(state)')], unique=True)
    # ### end Alembic commands ###

    _backfill_locations()


def _backfill_locations() -> None:
    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT DISTINCT city, latitude, longitude FROM gas_fillups")).fetchall()

    by_city_state: dict[tuple[str, str], tuple[float | None, float | None]] = {}
    for raw_city, lat, long_ in rows:
        city, _, state = raw_city.partition(",")
        by_city_state[(city.strip(), state.strip())] = (lat, long_)

    locations_table = sa.table(
        "locations",
        sa.column("city", sa.Text),
        sa.column("state", sa.Text),
        sa.column("lat", sa.Numeric(9, 6)),
        sa.column("long", sa.Numeric(9, 6)),
    )
    conn.execute(
        locations_table.insert(),
        [
            {"city": city, "state": state, "lat": lat, "long": long_}
            for (city, state), (lat, long_) in by_city_state.items()
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_locations_city_state_lower', table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
