"""add locations table

Schema only -- data comes from seed.seed() (backend/seed/fixtures/locations.json),
which is the source of truth for locations going forward. (This revision
originally also backfilled rows here by mechanically splitting
gas_fillups.city on its first comma, but that path only ever ran correctly
against an already-populated gas_fillups table -- on a genuinely fresh
install, migrations run before seeding, so gas_fillups is empty at this
point and the backfill silently inserted nothing to insert an all-NULL row
instead, which violates the NOT NULL constraint. Backfilling here also
duplicated seed.seed() as a second, inferior source of truth: it re-derives
the same state-parsing mistakes seed.seed()'s fixture already has manual
fixes for. Removed once the fixture existed to replace it.)

Revision ID: f9f8c74f95a5
Revises: 853cc1c56d53
Create Date: 2026-08-12 10:10:03.524660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f8c74f95a5'
down_revision: Union[str, Sequence[str], None] = '853cc1c56d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('long', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_locations_city_state_lower', 'locations', [sa.literal_column('lower(city)'), sa.literal_column('lower(state)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_locations_city_state_lower', table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
